# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c9e6397ee7ac1be0ac907db432e5b77d79b328919d917e2dad8522979619eea3d09f9f83f27717c6e25897bd50b8357448e4212f1586da1d6c440628271fa409

test:
  secret_key_base: 801480464b3a94a974cedac46aada7385e9be3a66fdbd870e44cc3c8e92b807f682ce3c9c22b6b7591855a3844c158805a8b594a56e7550977e16808a5fb44e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
